### ISSUE TITLE
Support for NVIDIA's proprietary driver

### ISSUE THREAD

**Issue by Newbytee** [Plagman/gamescope#151]
Now that NVIDIA's proprietary driver is about to land support for GPU-accelerated XWayland[1], could we see gamescope supporting it?

 [1] https://gitlab.freedesktop.org/xorg/xserver/-/merge_requests/587

**Comment by emersion** [comment]
Maybe. They'd need to add support for Vulkan DMA-BUF extensions too.

We still have some code that assumes Mesa and AMD hardware (also see https://github.com/Plagman/gamescope/issues/49). We'll need to clean these up.

Keep in mind that because the driver is proprietary, it makes the gamescope work a lot more difficult. We've been routinely sending RADV and amdgpu patches upstream to fix bugs, and reading the source code for troubleshooting. This isn't possible with a proprietary driver.

**Comment by Samsagax** [comment]
Current build from git fails on Nvidia proprietary driver.

On my laptop:
````
gamescope -- glxgears
No CAP_SYS_NICE, falling back to regular-priority compute and threads.
Performance will be affected.
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

vulkan: selecting physical device 'NVIDIA GeForce 940M'
vulkan: physical device does not support DRM format modifiers
vulkan: supported DRM formats for sampling usage: 0x34325258, 0x34325241, 0x3231564E
Failed to initialize Vulkan
````
Since #51 and #49 are closed, and mesa 21.2.1 changes, what needs to happen to get Nvidia working?

**Comment by emersion** [comment]
They need to implement `VK_EXT_image_drm_format_modifier`.

**Comment by soredake** [comment]
https://vulkan.gpuinfo.org/listdevicescoverage.php?platform=linux&extension=VK_EXT_image_drm_format_modifier

**Comment by MagicRB** [comment]
Should this work already?

**Comment by emersion** [comment]
While NVIDIA is missing in the link above, no, this won't work.

**Comment by matteoturini** [comment]
nvidia should just open source their driver and be done with it

**Comment by MagicRB** [comment]
> While NVIDIA is missing in the link above, no, this won't work.

I thought that they did cause of the link, thanks for the info!

**Comment by MagicRB** [comment]
> nvidia should just open source their driver and be done with it

And Microsoft should remove spyware from Windows and people should always be nice to each other. We both know none of those things will happen so we just have to make due with what we have

**Comment by matteoturini** [comment]
its different, nvidia doesnt make money from nvidia drivers. windows makes money from spying. they should open source, or heck, allow unsigned firmware or lend a key to nouveau developers sign the firmware.

**Comment by meisme-dev** [comment]
Is there any hope for NVIDIA to implement this?

**Comment by TLATER** [comment]
This place isn't NVIDIA support. If you'd like to know their plans, email them, and maybe share it here if it's relevant to closing this issue.

To actually be a bit helpful: 

---

Nvidia *have* slowly been adding bits of support for Wayland-related features to the proprietary driver, but it's also been like half a decade since the move to Wayland started, so who knows.

Their message is obviously, in the future, don't buy nvidia if you're planning to use a Linux desktop.

You can try the FOSS driver (nouveau) if you're desperate, but it'll most likely run ridiculously slowly compared to the proprietary one. I'm personally sticking to X until I either buy a new GPU or nvidia see the light.

---

All that said, little bit rude to ping everybody watching this issue with nvidia rants/questions, for future readers, please just click the subscribe button and wait for someone to share some news.

Until there's a comment with news, people here know as much as you do, and we're all as annoyed by the proprietary software from this vendor as you are.

**Comment by matteoturini** [comment]
My next GPU definitely won't be NVIDIA.

But I can't get a GPU until supply chain gets fixed up and miners calm down.

**Comment by MagicRB** [comment]
#454

**Comment by sigboe** [comment]
Seams an official Nvidia employee says gamescope required vulkan extensions soon™

https://forums.developer.nvidia.com/t/request-for-gamescope-and-the-vk-ext-image-drm-format-modifier/208614

**Comment by sad-goldfish** [comment]
It seems, nvidia has added support for this with their most recent driver [here](https://www.nvidia.com/download/driverResults.aspx/187834/en).

**Comment by emersion** [comment]
Yup. Closing since there's nothing more to be done on the gamescope side.

**Comment by iMonZ** [comment]
This means NVIDIA GPU should automatically work now?
If yes the next question is, how to get steamos running on NVIDIA hardware

**Comment by matteoturini** [comment]
> This means NVIDIA GPU should automatically work now? If yes the next question is, how to get steamos running on NVIDIA hardware

well that's not a gamescope issue

**Comment by nrdxp** [comment]
Just to confirm, has anyone got this working on the aforementioned beta driver, or the recently release 515.48.07?

**Comment by IceDBorn** [comment]
I got it working by using gamescope-git (Arch)

**Comment by SingerJonathan** [comment]
> @nrdxp I got it working by using gamescope-git (Arch)

Were you able to get it working with fullscreen? For me it's only working in borderless and windowed modes with 515.48.07. If I launch in fullscreen or switch to fullscreen after launching, gamescope output goes black and I have to terminate it, at which point it freezes everything for about 10 seconds.

**Comment by IceDBorn** [comment]
@SingerJonathan Nope, using the -f flag, renders the first frame and then gamescope hangs.
