### ISSUE TITLE
3.11.0beta4 causes Steam games fail to launch

### ISSUE THREAD

**Issue by Hydranet** [Plagman/gamescope#382]
I reported it as a [bug](https://bugs.archlinux.org/task/73531) for Arch community packages but since the source is the github project, I thought
I would also make a report here.

Description: When updating from 3.10.7 to  3.11.0beta4 Steam games fail to launch, X seems to get terminated.

Additional info:
* package version(s): 3.11.0beta4-1, current working stable version is 3.10.7
* config and/or log files etc. See attachment
[steam_terminaloutput.txt](https://github.com/Plagman/gamescope/files/7960907/steam_terminaloutput.txt)

Steps to reproduce:
1. Update gamescope: package upgrade (3.10.7-1 => 3.11.0beta4-1)
2. Launch Steam and try to launch game
3. Game fails to launch because X is terminated
4. Downgrade back to the current version(3.10.7) of gamescope.
5. Reboot system since without reboot the problem persists
6. Open Steam and launch game with 3.10.7-1 installed and games launch as usual again.

**Comment by IDDQD69** [comment]
same for me with 3.10.8 and 3.11.0-beta12

Using x11 with AMD gpu.

[log_file.txt](https://github.com/Plagman/gamescope/files/7980159/log_file.txt)

**Comment by gbj1viciado** [comment]
Try to disable the steam overlay.

**Comment by Boxieharp** [comment]
Just to add to this, same behavior occurs with 3.11.0beta6-1. It only happens when trying to open Steam or any game launched through steam with gamescope enabled. If you have a game in Lutris that has gamescope enabled, it will launch fine. However, if you add the same Lutris executable of that game to steam as a "Non-steam game" and launch it that way, it will fail to open.

> Try to disable the steam overlay.
As mentioned by @gbj1viciado, disabling the overlay will allow the game to launch normally. However you will miss on features that require the Steam Overlay such as Steam Input.

This happens both with the runtime and native versions of Steam.

**Comment by IDDQD69** [comment]
> Try to disable the steam overlay.

yes. Thins works most of the time. but not for witcher 3 for some reason.
