### ISSUE TITLE
Get layers working consistently

### ISSUE THREAD

**Issue by Plagman** [Plagman/gamescope#41]
libliftoff is hooked up with -l, and Roman has done some fixes already, but doesn't seem to work reliably still. Would be really nice to get that 100% robust on amdgpu so we could have the FPS meter or notifications up without killing perf.

**Comment by subdiff** [comment]
There are currently three issues I'm aware of:

### Cursor cap not respected
A notification window might end up on the cursor plane because the AMD driver does not check for cursor cap when doing an atomic test commit.

Simon has a patch for that on [the mailing list](https://lists.freedesktop.org/archives/amd-gfx/2020-March/047825.html). I had opened [a ticket](https://github.com/emersion/libliftoff/issues/46) for that issue some time ago in libliftoff. If the patch will be further stalled for kernel inclusion I would like to have the check in libliftoff instead.

### Layer properties mismatch
Properties on libliftoff layers are not "reset" when a layer is reallocated. This leads to sub-optimal or even broken allocations over time.

In our case the Steam overlay is blended in via the overlay alpha property. This alpha property is never kept afterwards with the same value on the libliftoff layer.

But I changed the code such that the alpha is only set when it is smaller 1 (otherwise the primary plane could never be used). That means if you blend out the Steam overlay and afterwards allocate a notification window to the overlay plane the notification will be invisible.

I had some ideas how to solve this issue in libliftoff but wanted to wait with formulating them out in the [issue ticket](https://github.com/emersion/libliftoff/issues/45) I created after Simon expressed some own thoughts about it. Since he is the maintainer and this could be a rather large change of the current architecture I thought I give him some time for developing a solution. But I will add some more details now.

An alternative solution right now for gamescope would be to reserve the first layer for the primary plane only and never set the alpha there. Have a second layer only for the overlay, always set the alpha there and a third layer potentially only for the cursor also never setting there the alpha. If the hardware supports more than one overlay a fourth can be used exclusively for notifications and without alpha.

### Missing fallback to composition layer
We currently don't use the compositing layer in case the allocation fails but recreate a new layer allocation.

**Comment by emersion** [comment]
Since https://github.com/emersion/libliftoff/commit/44946c44d849dddd0c79a003c7ab5013703856bf setting alpha = 1 should work even with hw planes that don't support the alpha property.

>Cursor cap not respected

amdgpu fix is merged in stable trees.

>Layer properties mismatch

Since we always set all properties on all layers, this should be fine for now. Would still be nice to fix in libliftoff of course.
