### ISSUE TITLE
Screen left in HDR colorspace after exiting gamescope.

### ISSUE THREAD

**Issue by msxmine** [Plagman/gamescope#769]
Currently gamescope doesn't seem to restore the screen back to SDR upon exit.
This causes everything else on the system (linux vt, sddm, kde, etc.) to appear too bright and saturated.
Gamescope should restore all output properties to how they were originally.

**Comment by rialpa84** [comment]
In my experiences that is more likely to happen when I try games that have HDR support but don't detect that Gamescope/DXVK/Linux-6.2/Proton/Wine/??? also supports HDR. Hitman 2 and Resident Evil 2 are big offenders here. With games that work, like FFVII from EGS, it usually exits just fine.

I can trigger the same effect launching those games -- instead of the game launching the screen sometimes goes black and goes back to SDDM.

I can also trigger it occasionally when exiting games some games. There's a crash somewhere between exiting the game and the Steam BPM coming back.

Your pull request from the other day seems to help with it in regards to exiting games where HDR is detected and working. FFVII from the EGS hasn't done that to me since I tried your PR. Granted, sometimes I have to launch that game twice since HDR won't be picked up the first time (both before and after your PR).

How are you launching Gamescope for HDR? I modified gamescope-session-git from the AUR so I'm launching Steam BPM in HDR and then my games from there (including EGS games). I think that gamescope script helps here since there are a couple of commands near the end to make sure gamecope is completely killed when exiting the Steam BPM.

Because there are so many moving pieces here I have no idea what logs, etc that I need to share.

**Comment by Joshua-Ashton** [comment]
This is not possible, other compositors need to be aware of the properties we set. If you close Gamescope cleanly it will not happen. You can also re-open and close Gamescope to fix it.

**Comment by rialpa84** [comment]
I can assure you it happens when crashes occur. It's like the AMDGPU driver itself doesn't stop doing HDR. The problem, as far as I see it, is that AMDGPU doesn't handle going from HDR to SDR when an HDR enabled application crashes and the system should go back to rendering in SDR.

I've tried reopening and closing Gamescope, both launching it manually and via a session script, but that usually results in a black screen upon opening Gamescope and I find that rebooting my PC seems to be the best fix.

**Comment by msxmine** [comment]
Oh, I may have been killing gamescope with a SIGHUP because of a scripting error.
Anyway, the crash handling issue still stands. Is there some debugfs interface or a small wrapper/utility that would reset the output to BT709/sRGB? Also, am I misinterpreting how HDR in gamescope works? For me the display stays in HDR mode the whole time it's running. Even when showing SDR content. SDR is limited brigtness wise to whatever I set it to, but still looks either too washed out, or too saturated (when wrongly interpreting it as BT2020). (That may be on my TV not oversaturating everything when in HDR mode though). Also obviously because of the limited bits when mapping SDR, gradients look much worse. It would be best to only switch to HDR when a game is requesting it. Would such dynamic modesetting be possible? (HDR for HDR-aware games, HDR with mapping for mixed content and SDR for SDR content)

**Comment by Joshua-Ashton** [comment]
If SDR games look washed out, you are likely missing my kernel which fixes the colorimetry packet.

There is also `--hdr-wide-gammut-for-sdr`

If you want to reset back to SDR, the best way is to just restart and close gamescope in SDR right now. Sorry.

**Comment by Joshua-Ashton** [comment]
I have considered automatically switching, but it would involve a modeset most-likely, which is kinda urksome and long on external displays.

**Comment by flakey-bit** [comment]
I'm (I think) encountering this issue. 

On my HTPC I switch between Kodi (media centre) and Steam (which runs under SDDM + gamescope). When exiting Steam and returning to Kodi, the colours are all washed out. I currently have to restart to fix it. 

I've tried disabling HDR in Steam - no avail. 

My scripting for switching between the two basically amounts to having systemd stop the sddm service and start the kodi service. 

What should I do to make sure that gamescope exits cleanly?

**Comment by msxmine** [comment]
I run kodi on bare Xorg and steam on bare gamescope (I have a session management script and a kodi addon that connects to it)
I found that the easiest solution is to just run vkcube in a new SDR gamescope instance for a few seconds after the main steam gamescope HDR instance exits
